# Generated by Django 5.2.16 on 2026-07-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GayaCopywriting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Gaya (Contoh: Casual)')),
                ('prompt', models.TextField(verbose_name='Instruksi AI (Contoh: Gunakan bahasa santai, gaul, dan kekinian)')),
            ],
        ),
    ]
