# Generated by Django 5.2.16 on 2026-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('ig_access_token', models.TextField(blank=True, null=True)),
                ('ig_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gayacopywriting',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gayacopywriting',
            name='prompt',
            field=models.TextField(),
        ),
    ]
