# Generated by Django 5.2.16 on 2026-07-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0002_pengaturanapi_alter_gayacopywriting_nama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanapi',
            name='cloudinary_creds',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kredensial Cloudinary'),
        ),
        migrations.AlterField(
            model_name='pengaturanapi',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key Gemini'),
        ),
        migrations.AlterField(
            model_name='pengaturanapi',
            name='ig_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token Akses IG'),
        ),
        migrations.AlterField(
            model_name='pengaturanapi',
            name='ig_account_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Akun IG'),
        ),
    ]
