# Generated by Django 5.2.16 on 2026-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0003_pengaturanapi_cloudinary_creds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanapi',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI (ChatGPT) / Groq')], default='gemini', max_length=20, verbose_name='Penyedia AI Aktif'),
        ),
        migrations.AddField(
            model_name='pengaturanapi',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key OpenAI/Groq'),
        ),
    ]
