# Generated by Django 5.2.16 on 2026-07-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0004_pengaturanapi_ai_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturanapi',
            name='openai_api_key',
        ),
        migrations.AddField(
            model_name='pengaturanapi',
            name='gemini_model',
            field=models.CharField(default='gemini-1.5-flash-latest', max_length=100, verbose_name='Nama Model Gemini'),
        ),
        migrations.AddField(
            model_name='pengaturanapi',
            name='groq_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key Groq'),
        ),
        migrations.AddField(
            model_name='pengaturanapi',
            name='groq_model',
            field=models.CharField(default='llama-3.3-70b-versatile', max_length=100, verbose_name='Nama Model Groq'),
        ),
        migrations.AddField(
            model_name='pengaturanapi',
            name='openrouter_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key OpenRouter'),
        ),
        migrations.AddField(
            model_name='pengaturanapi',
            name='openrouter_model',
            field=models.CharField(default='google/gemini-2.0-flash-exp:free', max_length=100, verbose_name='Nama Model OpenRouter'),
        ),
        migrations.AlterField(
            model_name='pengaturanapi',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini (Native)'), ('groq', 'Groq (Llama, Sangat Cepat)'), ('openrouter', 'OpenRouter (Akses Multi-AI)')], default='gemini', max_length=20, verbose_name='Penyedia AI Aktif'),
        ),
    ]
