# Generated by Django 5.2.16 on 2026-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0005_remove_pengaturanapi_openai_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturanapi',
            name='openrouter_api_key',
        ),
        migrations.RemoveField(
            model_name='pengaturanapi',
            name='openrouter_model',
        ),
        migrations.AlterField(
            model_name='pengaturanapi',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('groq', 'Groq Cloud')], default='gemini', max_length=20, verbose_name='Penyedia AI Aktif'),
        ),
    ]
