# Generated by Django 5.2.16 on 2026-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0006_remove_pengaturanapi_openrouter_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaturanapi',
            name='gemini_model',
            field=models.CharField(default='gemini-flash-latest', max_length=100, verbose_name='Nama Model Gemini'),
        ),
    ]
