# Generated by Django 5.2.16 on 2026-07-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0007_alter_pengaturanapi_gemini_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Bidang Usaha')),
                ('ikon', models.CharField(default='📌', help_text='Gunakan Emoji/Ikon (Contoh: 🍔)', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Bidang Usaha',
            },
        ),
        migrations.CreateModel(
            name='FieldBidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Teks yang tampil, Contoh: Nama Resto/Cafe', max_length=100)),
                ('name_attribute', models.SlugField(help_text='Variabel sistem (Huruf kecil & tanpa spasi), Contoh: nama_resto')),
                ('placeholder', models.CharField(blank=True, help_text='Teks bayangan di dalam kotak', max_length=150, null=True)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='caption_app.bidangusaha')),
            ],
        ),
    ]
