# Generated by Django 5.2.16 on 2026-08-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0008_bidangusaha_fieldbidang'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanapi',
            name='fb_app_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook App ID'),
        ),
        migrations.AddField(
            model_name='pengaturanapi',
            name='fb_app_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook App Secret'),
        ),
        migrations.AlterField(
            model_name='bidangusaha',
            name='ikon',
            field=models.CharField(default='📌', help_text='Gunakan Emoji/Ikon', max_length=20),
        ),
    ]
