# Generated by Django 5.2.16 on 2026-08-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0009_pengaturanapi_fb_app_id_pengaturanapi_fb_app_secret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidangusaha',
            options={'verbose_name_plural': 'Kategori Konten'},
        ),
        migrations.AlterModelOptions(
            name='gayacopywriting',
            options={'verbose_name_plural': 'Gaya Copywriting'},
        ),
        migrations.AlterModelOptions(
            name='pengaturanapi',
            options={'verbose_name_plural': 'Pengaturan API & Sistem'},
        ),
        migrations.AddField(
            model_name='fieldbidang',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Wajib Diisi?'),
        ),
        migrations.AddField(
            model_name='fieldbidang',
            name='tipe_field',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Textarea / Paragraf'), ('select', 'Dropdown Select'), ('date', 'Tanggal / Date')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='bidangusaha',
            name='nama',
            field=models.CharField(max_length=100, verbose_name='Kategori Konten'),
        ),
        migrations.AlterField(
            model_name='fieldbidang',
            name='label',
            field=models.CharField(help_text='Teks yang tampil, Contoh: Nama Regulasi / Lokasi Acara', max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldbidang',
            name='name_attribute',
            field=models.SlugField(help_text='Variabel sistem (Huruf kecil & tanpa spasi), Contoh: nama_regulasi'),
        ),
        migrations.AlterField(
            model_name='gayacopywriting',
            name='prompt',
            field=models.TextField(help_text='Gunakan placeholder seperti {topik}, {poin_utama}, {cta}, dll.'),
        ),
        migrations.CreateModel(
            name='KontenPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_form_data', models.JSONField(default=dict, help_text='Menyimpan pasangan {name_attribute: value} dari FieldBidang')),
                ('media_url', models.URLField(max_length=500, verbose_name='URL File Media (Cloudinary/S3)')),
                ('tipe_media', models.CharField(choices=[('IMAGE', 'Single Image'), ('CAROUSEL', 'Carousel (Multiple Images)'), ('REELS', 'Reels / Video Short')], default='IMAGE', max_length=20)),
                ('caption_generated', models.TextField(verbose_name='Caption Hasil AI / Final')),
                ('hashtag', models.TextField(blank=True, help_text='Tagar wajib instansi & tagar tambahan', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / AI Generated'), ('PENDING_APPROVAL', 'Menunggu Persetujuan Humas'), ('APPROVED', 'Disetujui (Siap Posting / Terjadwal)'), ('REJECTED', 'Ditolak / Perlu Revisi'), ('PUBLISHED', 'Berhasil Dipublikasi'), ('FAILED', 'Gagal Dipublikasi')], default='DRAFT', max_length=20)),
                ('waktu_dijadwalkan', models.DateTimeField(blank=True, null=True, verbose_name='Jadwal Upload IG')),
                ('waktu_dipublikasi', models.DateTimeField(blank=True, null=True)),
                ('ig_post_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Postingan Instagram')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Log Error API (Jika Gagal)')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('gaya_copywriting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caption_app.gayacopywriting')),
                ('kategori_konten', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caption_app.bidangusaha')),
                ('pemohon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postingan_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Konten Postingan Instagram',
            },
        ),
        migrations.CreateModel(
            name='CatatanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_keputusan', models.CharField(choices=[('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak/Revisi')], max_length=20)),
                ('catatan_revisi', models.TextField(blank=True, help_text='Alasan penolakan atau instruksi revisi', null=True)),
                ('waktu_keputusan', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('konten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='caption_app.kontenposting')),
            ],
        ),
    ]
