# Generated by Django 5.2.17 on 2026-08-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0011_auto_20260807_0008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaturanapi',
            name='ig_access_token',
        ),
        migrations.RemoveField(
            model_name='pengaturanapi',
            name='ig_account_id',
        ),
        migrations.AlterField(
            model_name='kontenposting',
            name='dynamic_form_data',
            field=models.JSONField(blank=True, default=dict, help_text='Menyimpan pasangan {name_attribute: value} dari FieldBidang'),
        ),
        migrations.AlterField(
            model_name='kontenposting',
            name='media_url',
            field=models.TextField(verbose_name='URL File Media (Bisa JSON List untuk Carousel / Text URL)'),
        ),
        migrations.AlterField(
            model_name='pengaturanapi',
            name='cloudinary_creds',
            field=models.CharField(blank=True, help_text='Format: CloudName,APIKey,APISecret', max_length=255, null=True, verbose_name='Kredensial Cloudinary'),
        ),
        migrations.CreateModel(
            name='AkunInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_akun', models.CharField(help_text='Contoh: @humas_pemkot / @diskominfo', max_length=100)),
                ('ig_account_id', models.CharField(max_length=100, verbose_name='ID Akun Instagram')),
                ('ig_access_token', models.TextField(verbose_name='Token Akses IG (Long-Lived)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('pengelola', models.ManyToManyField(blank=True, help_text='User/Staff yang diizinkan mengunggah ke akun ini', related_name='akun_instagram_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Akun Instagram',
            },
        ),
        migrations.AddField(
            model_name='kontenposting',
            name='target_akun_ig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postingan', to='caption_app.akuninstagram', verbose_name='Target Akun Instagram'),
        ),
    ]
