# Generated by Django 5.2.17 on 2026-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0012_remove_pengaturanapi_ig_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanapi',
            name='ig_app_id',
            field=models.CharField(blank=True, help_text='Diambil dari App Dashboard → Instagram → API setup with Instagram login', max_length=100, null=True, verbose_name='Instagram App ID'),
        ),
        migrations.AddField(
            model_name='pengaturanapi',
            name='ig_app_secret',
            field=models.CharField(blank=True, help_text='Diambil dari App Dashboard → Instagram → API setup with Instagram login', max_length=255, null=True, verbose_name='Instagram App Secret'),
        ),
        migrations.AlterField(
            model_name='pengaturanapi',
            name='fb_app_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook App ID (Legacy, tidak dipakai lagi)'),
        ),
        migrations.AlterField(
            model_name='pengaturanapi',
            name='fb_app_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook App Secret (Legacy, tidak dipakai lagi)'),
        ),
    ]
