# Generated by Django 5.2.17 on 2026-08-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0013_pengaturanapi_ig_app_id_pengaturanapi_ig_app_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldbidang',
            name='pilihan_select',
            field=models.CharField(blank=True, help_text='Isi pilihan dipisah koma. Contoh: Aktif,Nonaktif,Pending', max_length=500, null=True, verbose_name='Pilihan (khusus tipe Dropdown Select)'),
        ),
    ]
