# Generated by Django 5.2.17 on 2026-08-23 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0014_fieldbidang_pilihan_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidangusaha',
            name='ikon_gambar',
            field=models.FileField(blank=True, help_text='Opsional. Unggah file ikon (SVG, PNG, JPG, GIF, atau WEBP). Kalau diisi, ini dipakai duluan daripada emoji di atas.', null=True, upload_to='ikon_bidang/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp'])], verbose_name='Ikon (File Gambar)'),
        ),
        migrations.AlterField(
            model_name='bidangusaha',
            name='ikon',
            field=models.CharField(blank=True, help_text='Opsional. Gunakan Emoji/Ikon teks, contoh: 📌. Boleh dikosongkan kalau pakai upload gambar di bawah.', max_length=20, null=True, verbose_name='Ikon (Emoji)'),
        ),
    ]
