# Generated by Django 5.2.17 on 2026-08-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0015_bidangusaha_ikon_gambar_alter_bidangusaha_ikon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenggunaBiasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon')),
                ('password', models.CharField(max_length=255, verbose_name='Password (Hash)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Terdaftar Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Pengguna',
                'verbose_name_plural': 'Daftar Pengguna',
                'ordering': ['-created_at'],
            },
        ),
    ]
