# Generated by Django 5.2.17 on 2026-08-25 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_app', '0016_penggunabiasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akuninstagram',
            name='pengelola',
            field=models.ManyToManyField(blank=True, help_text='Pengguna Biasa yang diizinkan mengunggah ke akun ini', related_name='akun_instagram_list', to='caption_app.penggunabiasa'),
        ),
        migrations.AlterField(
            model_name='kontenposting',
            name='pemohon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postingan_dibuat', to='caption_app.penggunabiasa'),
        ),
    ]
